#!/usr/bin/env python3 -u
# -*- coding: utf-8 -*-
"""
Project Euler: Problem 2
========================

https://projecteuler.net/problem=2

Even Fibonacci numbers
----------------------
Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will
be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""
from itertools import islice

import pytest


def fibonacci():
    """Yield Fibonacci numbers, starting with 1 and 2."""
    a, b = 1, 2
    while True:
        yield a
        a, b = b, a + b


def test_fibonacci():
    assert list(islice(fibonacci(), 10)) == [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


def even_elements_lte(n, seq):
    for element in seq:
        if element > n:
            return
        if not element & 1:
            yield element


def sum_of_even_fibonacci_numbers_lte(n):
    """Return the sum of all even-valued Fibonacci numbers <= n."""
    return sum(even_elements_lte(n, fibonacci()))


@pytest.mark.parametrize('n, expected', [
    (-1, 0),
    (0, 0),
    (1, 0),
    (2, 2),
    (8, 2 + 8),
    (89, 2 + 8 + 34),
    ])
def test_sum_of_even_fibonacci_numbers_lte(n, expected):
    assert sum_of_even_fibonacci_numbers_lte(n) == expected


if __name__ == '__main__':
    print(sum_of_even_fibonacci_numbers_lte(4e6))
